### ISSUE TITLE
Car file not generated (with TCC)

### ISSUE THREAD

**Issue by BartGo** [GienekP/menu4car#1]
Using Tiny C Compiler (https://bellard.org/tcc) on Windows 11 (using Git's bash), compiled menu4car.exe:
./i386-win32-tcc.exe ./menu4car.c

The compiled file seems to execute correctly:
$ ./menu4car.exe
Menu4CAR - ver: Oct 15 2023
(c) GienekP
use:
menu4car menu.txt file.car

I am using a simple config file:
$ cat ./menu4car.txt
Misja|Misja.xex
Scorch|Scorch.xex

Trying to generate the "car" file:
$ ./menu4car.exe ./menu4car.txt BG1.car
Menu4CAR - ver: Oct 15 2023

No "car" file is being generated.

If TCC is not right, please describe a process and tools to compile the application.

**Comment by GienekP** [comment]
Try to use my compilation:
https://github.com/GienekP/menu4car/releases/tag/20231015

W dniu 15.10.2023 o 22:08, BartGo pisze:

**Comment by BartGo** [comment]
Ah, works fine with that.
