### ISSUE TITLE
Skok do c2c8

### ISSUE THREAD

**Issue by jhusak** [GienekP/menu4car#2]
Hej. Jako "failsafe" gdy bank jest źle ustawiony, lub w starym AtariMax, masz po wyzerowaniu banku skok do C2C8 (RESETCD, wziety z wZiętary zapewne :D)  Raczej bym resetował przez e477, który jest zawsze tutaj. Piszę, bo nie wiem, jaki był zamysł :)

**Comment by GienekP** [comment]
Tak. Było według Zientary. Dajemy $E477 dla większej kompatybilności.

**Comment by jhusak** [comment]
Zamieniono na E477.
