### ISSUE TITLE
eaeaeaea

### ISSUE THREAD

**Issue by jhusak** [GienekP/menu4car#3]
W reszcie karta jest eaeaea.... Czy to po to, żeby ffff nie czytał dalej? Co, jak się zamieni na eaea (czy na 0000) 2 bajty po końcu pliku, a potem to już ffffff? To oszczedzi flash i przyspieszy flashowanie mniej zapełnionych kartów.

**Comment by GienekP** [comment]
$EA (NOP) tylko do testów, wykrywania błędów wynikających ze specyfiki maxflasha. Docelowo $FF.

**Comment by jhusak** [comment]
Zrobione - zamieniono na FF.
