### ISSUE TITLE
Użycie rozszerzonej składni mads

### ISSUE THREAD

**Issue by jhusak** [GienekP/menu4car#5]
Jak się zapatrujesz na używanie rozszerzonej składni madsa?

inw zamiast inc bne inc itd?

**Comment by GienekP** [comment]
Nie stosuję, bo zaciemnia to troszkę wielkość kodu.

**Comment by jhusak** [comment]
Ale zwiększa czytelność i umożliwia optymalizację typu usuwanie jsr do 3 instrukcji... Ale nie upieram się :) Makr też nie używasz z ww powodu? Pytam tylko, bo ja nie jestem uzdolniony obserwacyjnie i muszę skracać zapis, żeby go lepiej widzieć. A z czasem wytwarza się instynkt "a to makro to zajmuje 10 bajów". Takie jsr-y też są kosztowne - ca 12 cykli idzie w pustkę. A chcąc jeszcze tam dekompresję wrzucić i żeby to działało kilka sekund, to trzeba pilnować wydajności :)

**Comment by GienekP** [comment]
Do tej pory miałem do czynienia z wpasowaniem się do istniejących kodów i wtedy trzeba wstrzelać się co do bajta. No a wtedy Makra generują tylko kłopot. Tak samo jak się testuje i zmienia się kod gdzie jest mijanka pomiędzy flash a ram. Czasem pół makra wypadałoby dać w ram a drugie pół we flashu. Inaczej jest jak już jest gotowiec i wywala się niepotrzebny kod. Z tym, że makro nie zmniejsza kodu robi tylko czytelniejszą iluzję. Inna sprawa, jak już wiadomo, co i jak i się robi optymalizację pod konkret, bo wiadomo, że inaczej już nie będzie. Wtedy to ma sens.

**Comment by jhusak** [comment]
To ja będę robił w miarę wstrzemięźliwie, ale będę stosował wygodne makra czy ficzery madsa tam, gdzie to jest uzasadnione.
