### ISSUE TITLE
MSB bank

### ISSUE THREAD

**Issue by jhusak** [GienekP/menu4car#6]
Jakie zastosowanie ma MSB bank w table? Czy jest jakiś kartridż, co z tego skorzysta? Pytam, bo przydałby mi się tam bit oznaczający kompresję, nie chcę polegać na nagłówku dosu - że jeśli inny to kompresja. Poza tym jak go bierzesz jako MSB, to robisz <<7. Wydaje mi się, że powinno być już jako <<8, bo to MSByte a nie MS7bit. Czy mogę to usunąć i dać tam "flags"?

**Comment by GienekP** [comment]
Tak. Jest błąd. I nie jest używane (dlatego nie wyłapałem buga). Miało być przyszłościowo dla RAMCARta gdzie banków jest więcej niż 255 ale nie da się za bardzo tego pogodzić. Daj FLAGS i przyszłościowo daj jeden BIT, że jest to plik ATR ;)

**Comment by GienekP** [comment]
Daj przyszłościowo jeszcze JEDEN BIT w FLAGS dla pliku BOOT. Będzie można przenieś różne plik z kasety, chociażby słynny wykrzyknik. Oraz wszelakie "turba" wczytywane właśnie jako BOOT :)

**Comment by jhusak** [comment]
Będą 2 pola,: 3 bity: 0-7 kompresja oraz 3 bity typ: 0-xex. 1-boot, 2-atr, 3-basic,4 car 8kB. Jeszcze 1 bit zostaje (bo najstarszy zajęty).
Car 8kb mapowany bezpośrednio, bez wczytywania.
Bardzo fajny ten pomysł z krótkim handlerem na stosie. Genialne a praktycznie nie zajmuje pamięci :)

**Comment by GienekP** [comment]
Właśnie miałem Ci pisać o CAR-8kB :) hehe Bo dla tych cartów trzeba było specjalnie robić 512kB i się marnowało a tak wszystkie stare "Turba" "loadery" będzie można zamknąć w jednym menu ;) 
JEST DOBRZE ! 👍

**Comment by jhusak** [comment]
Co do car mam pomysł, żeby je dawać od końca, a pliki zmiennej długości od początku, jak jest. Jest tylko problem z liczeniem końca pliku wtedy. Można to ogarnąć, ale może jest lepszy/prostszy sposób?

**Comment by GienekP** [comment]
Dobry pomysł. Tylko zaokrąglenie "od końca" musi iść  w skokach 128kB. Dzięki temu będzie można działać na pamięciach 128kB/256kB/512kB. Czyli jak składanka mieści się w 128kB to CAR idą od 128kB w dół. Jak 256 to od 256...

**Comment by jhusak** [comment]
Tak - dorobiłem swicze i w "-s" można dać 32-1024 w skokach co potęga dwójki. Pewnie nie ma kartridży 32 kB w tym bankowaniu, ale może ktoś sobie zrobi :) Dzisiaj pokomitowałem chyba ostatnie zmiany przed dorobieniem czy to kartridży, czy to zapisu xex-programera. Oprogramowanie jest przygotowane na 4 strony - powinno wystarczyć na gierki 8KB. Daje to max 104 wpisy.

**Comment by jhusak** [comment]
Dobra, zrobione kartridże. Kartridże są upychane po 8 kb od początku kartridża, a egzeki są za nimi, stąd konieczne było dodanie piątego elementu w tablicy plików - pozycji (bo fizycznie pozycje na kartridżu różnią się od wypisanych na ekranie. Przy okazji musiałem uprościć i zmienić procedurę upychającą, bo wymykał mi się obraz co i jak. A teraz jest tak.. puściej :)
